name: C++ Build

on:
    workflow_dispatch:
    pull_request:
      branches:
        - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Set branch name
              id: set-branch-name
              run: |
                  if [ "${{ github.event_name }}" = "pull_request" ]; then
                    echo "branch_name=${{ github.head_ref }}" >> $GITHUB_ENV
                  elif [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
                    branch=$(echo "${{ github.ref }}" | sed 's|refs/heads/||')
                    echo "branch_name=${branch}" >> $GITHUB_ENV
                  else
                    echo "branch_name=${{ github.ref }}" >> $GITHUB_ENV
                  fi

            - name: Use branch name
              run: echo "Branch name is ${{ env.branch_name }}"
              
            - name: Set up C++ environment
              run: sudo apt-get install -y g++ make

            - name: Checkout branch
              uses: actions/checkout@v2

            - name: Build with make
              run: |
                  ls
                  make clean && make
                  ./hello
                  make clean
                  if [ $? -eq 0 ]; then
                    echo "Build successful"
                  else
                    echo "Build failed"
                    exit 1
                  fi
            - name: Merge pull request
              if: success()
              run: |
                PR_NUMBER=$(echo "${{ github.event.pull_request.number }}")
                curl -s -X PUT \
                -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                -H "Accept: application/vnd.github.v3+json" \
                https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER/merge \
                -d '{"commit_title":"Merging PR #'"$PR_NUMBER"'","merge_method":"merge"}'
