name: C++ Build

on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up C++ environment
              run: sudo apt-get install -y g++ make

            - name: Build with make
              run: |
                make
                if [ $? -eq 0 ]; then
                  echo "Build successful"
                else
                  echo "Build failed"
                  exit 1
                fi
