name: C++ Build

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout branch
        run: |
          cd ~/actions_test
          git restore --staged .
          git checkout .
          git fetch
          git checkout ${{ github.head_ref }}
          git pull

      - name: Check for CODEOWNERS change
        run: |
          echo "Checking for changes from ${{ github.base_ref }} to ${{ github.head_ref }}"
          if git diff --name-only origin/${{ github.base_ref }}...origin/${{ github.head_ref }} | grep '.github/CODEOWNERS'; then
            echo "Modification to CODEOWNERS file is not allowed in this pull request."
            exit 1
          fi

      - name: Build with make
        run: |
          ls
          cd ~/actions_test
          make clean && make
          ./hello
          make clean
          if [ $? -eq 0 ]; then
            echo "Build successful"
          else
            echo "Build failed"
            exit 1
          fi

      # - name: Trigger merge workflow
      #   if: ${{ github.event_name == 'pull_request' }}
      #   run: |
      #     PR_NUMBER=${{ github.event.pull_request.number }}
      #     REPO_OWNER=${{ github.repository_owner }}
      #     REPO_NAME=$(basename ${{ github.repository }})
      #     curl -X POST \
      #       -H "Accept: application/vnd.github.v3+json" \
      #       -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
      #       https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/dispatches \
      #       -d '{"event_type":"merge_pull_request","client_payload":{"pr_number":'"$PR_NUMBER"'}}'
