name: C++ Build

on:
    workflow_dispatch:

jobs:
    build:
        runs-on: self-hosted

        steps:
            - name: Set up C++ environment
              run: sudo apt-get install -y g++ make

            - name: Checkout branch
              run: |
                  branch=$(echo "${{ github.ref }}" | sed 's|refs/heads/||')
                  cd ~/actions_test
                  git fetch
                  git checkout $branch
                  git checkout .
                  git pull

            - name: Build with make
              run: |
                  cd /home/lume/actions_test
                  make clean && make
                  ./hello
                  make clean
                  if [ $? -eq 0 ]; then
                    echo "Build successful"
                  else
                    echo "Build failed"
                    exit 1
                  fi
