name: Script Runner

on:
  workflow_dispatch:

jobs:
  run_script_and_print_message:
    runs-on: ubuntu-latest

    steps:
    - name: Run Script on Remote Server
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: dev.occ.lumerobotics.ai
        username: lume
        key: ${{ secrets.KEY }}
        script: |
          cd lume_monitor
          git config --global credential.helper store
          git config --global user.name "${{ secrets.USERNAME }}"
          git config --global user.password "${{ secrets.TOKEN_GITHUB }}"
          git pull
          ./scripts/start_lume_occ.sh
