name: Script Runner

on:
  workflow_dispatch:

jobs:
  run_script_and_print_message:
    runs-on: ubuntu-latest

    steps:
    - name: Run Script
      run: |
          echo "${{ secrets.KEY }}"
          echo "$KEY"
      env:
        KEY: ${{ secrets.KEY }}
