name: Script Runner

on:
  workflow_dispatch:

jobs:
  run_script_and_print_message:
    runs-on: ubuntu-latest

    steps:
    - name: Run Script on Remote Server
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: dev.occ.lumerobotics.ai
        username: lume
        key: ${{ secrets.KEY }}
        script: |
          cd lume_monitor
          git pull https://${{ secrets.USERNAME }}:${{ secrets.TOKEN_GITHUB }}@github.com/LumeRobotics/lume_monitor.git
          ./scripts/start_lume_occ.sh
