name: CI

on:
  push:
  workflow_dispatch:

jobs:
  run_script_and_print_message:
    runs-on: self-hosted

    steps:
    - name: Run Script
      run: |
        # Comando para executar o script (substitua pelo comando real)
        cd ~
        ./teste.sh

      continue-on-error: true

    - name: Print Message
      if: ${{ job.status == 'success' }}
      run: echo "O script foi executado com sucesso."
    
    - name: Print Message
      if: ${{ job.status != 'success' }}
      run: echo "O script falhou."
