name: CI

on:
  push:
  workflow_dispatch:

jobs:
  run_script_and_print_message:
    runs-on: self-hosted

    steps:
    - name: Run Script
      run: |
        # Comando para executar o script (substitua pelo comando real)
        cd ~
        ./teste.sh

    - name: Check Script Result
      id: check_result
      run: echo "::set-output name=script_exit_code::$?"

    - name: Print Message
      if: ${{ steps.check_result.outputs.script_exit_code == 0 }}
      run: echo "O script foi executado com sucesso."
    
    - name: Print Message
      if: ${{ steps.check_result.outputs.script_exit_code != 0 }}
      run: echo "O script falhou."
