name: Script Runner

on:
  workflow_dispatch:

jobs:
  run_script_and_print_message:
    runs-on: ubuntu-latest

    steps:
    - name: Run Script
      run: |
        ssh -i ${{ secrets.ssh_key }} lume@dev.occ.lumerobotics.ai
        cd lume_monitor
        git pull
        ./scripts/start_lume_occ
